# Generated by Django 4.2.6 on 2023-10-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_koder_options_codermessege_activcoder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='koder',
            old_name='kod',
            new_name='coder_cod',
        ),
    ]
