<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_kod_koder_coder_cod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmember',
            name='is_staff',
        ),
    ]
=======
# Generated by Django 4.2.6 on 2023-10-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_kod_koder_coder_cod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmember',
            name='is_staff',
        ),
    ]
>>>>>>> d51e158 (..)
