# Generated by Django 4.2.6 on 2023-10-26 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_boardmember_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codermessege',
            name='board',
        ),
        migrations.RemoveField(
            model_name='codermessege',
            name='inviter',
        ),
        migrations.RemoveField(
            model_name='codermessege',
            name='user',
        ),
        migrations.RemoveField(
            model_name='koder',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivCoder',
        ),
        migrations.DeleteModel(
            name='CoderMessege',
        ),
        migrations.DeleteModel(
            name='Koder',
        ),
    ]
