<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_codermessege_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardmember',
            name='is_activ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='token',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
=======
# Generated by Django 4.2.6 on 2023-10-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_codermessege_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardmember',
            name='is_activ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='token',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
>>>>>>> d51e158 (..)
